fixing bug in order of  announcements lines
aboueleyes/cms-downloader pull request #24
Opened 2021-04-21 19:08 UTC by ShimaaBetah

2021-04-21 19:20 UTC, aboueleyes requested changes
what's the point of the end_node function?

2021-04-21 22:55 UTC, ShimaaBetah commented
It is redundant I should remove it

2021-04-21 23:21 UTC, aboueleyes commented
okay waiting!

2021-04-23 00:54 UTC, ShimaaBetah commented
done

2021-04-23 11:07 UTC, aboueleyes approved these changes

2021-04-23 11:07 UTC, merged